---
title: "Section 1"
author: "Mamadou NDIAYE"
date: "2023-07-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Section 1 : Installation de l'environnemnt de travail

```{r}
library(ggplot2)
library(ggalt)
library(ggExtra)
library(ggcorrplot)
library(plotly)
library(quantmod)
library(ggthemes)
library(waffle)
library(highcharter)
library(dplyr)
library(ggfortify)
```

# Section 2 : Création des graphiques de corrélation

## Nuage de points

```{r}
theme_set(theme_bw())
data("midwest", package = "ggplot2")
head(midwest)
```

```{r}
gg <- ggplot(data = midwest, aes(x = area, y = poptotal)) +
  geom_point()
gg
```



```{r}
gg <- ggplot(data = midwest, aes(x = area, y = poptotal)) +
  geom_point(aes(col = state, size = popdensity))
gg
```


```{r, message=FALSE, warning=FALSE}
gg <- ggplot(data = midwest, aes(x = area, y = poptotal)) +
  geom_point(aes(col = state, size = popdensity)) +
  geom_smooth(method = "lm", se=T)
gg
```

```{r, message=FALSE, warning=FALSE}
gg <- ggplot(data = midwest, aes(x = area, y = poptotal)) +
  geom_point(aes(col = state, size = popdensity)) +
  geom_smooth(method = "lm", se = F) +
  xlim(c(0, 0.1)) +
  ylim(c(0, 500000)) +
  labs(subtitle = "Surface vs Population",
       y = "Population totale",
       x = "Surface",
       title = "Nuage de points de la population en fonction de la surface du comté",
       caption = "Source: midwest dataset")
gg
```
```{r message=FALSE, warning=FALSE}
ggplotly(gg)
```


```{r}
midwest_select <- midwest[midwest$poptotal > 350000 & 
                     midwest$poptotal <= 500000 & 
                     midwest$area > 0.01 &
                     midwest$area < 0.1,]
midwest_select
```

```{r message=FALSE, warning=FALSE}
g2 <- ggplot(data = midwest, aes(x = area, y = poptotal)) +
  geom_point(aes(col = state, size = popdensity)) +
  geom_smooth(method = "lm", se = F) +
  geom_encircle(aes(x = area, y = poptotal), data = midwest_select, color = 'red', size = 2, expand = 0.08) +
  xlim(c(0, 0.1)) +
  ylim(c(0, 500000)) +
  labs(subtitle = "Surface vs Population",
       y = "Population totale",
       x = "Surface",
       title = "Nuage de points de la population en fonction de la surface du comté",
       caption = "Source: midwest dataset")
g2
```


## Jitter plot : Nuage de points spécial

```{r}
data(mpg, package = "ggplot2")
head(mpg)
```


```{r, message=FALSE, warning=FALSE}
g <- ggplot(data = mpg, aes(x = cty, y = hwy))

g + geom_point() +
  geom_smooth(method = "lm") +
  labs(subtitle = "cty vs hwy",
       title = "Nuage de points avec des points qui se chevauchent",
       caption = "Source: mpg dataset")
```

```{r, message=FALSE, warning=FALSE}
theme_set(theme_light())
g <- g + geom_jitter(width = 0.5, size = 1) +
  geom_smooth(method = "lm") +
  labs(subtitle = "cty vs hwy",
       title = "Kilométrage autoroute en fcontion ville",
       caption = "Source: mpg dataset")
g
```

```{r, message = FALSE, warning=FALSE}
ggplotly(g)
```


## Graphique de décompte (*Counts charts*)

```{r}
g <- ggplot(mpg, aes(cty, hwy))

g <- g+geom_count(col = 'tomato3', show.legend = F) +
  labs(subtitle = 'cty vs hwy',
       title = "Kilométrage autoroute en fonction de kilométrage ville count charts")
g
```

```{r}
ggplotly(g)
```


## Graphique à buile (*Bubble plot*)

```{r}
mpg_select <- mpg[mpg$manufacturer %in% c("audi", "ford","honda", "hyunda"), ]
print(unique(mpg_select$manufacturer))
head(mpg_select)
```


```{r, message=FALSE, warning=FALSE}
g <- ggplot(mpg_select, aes(displ, cty)) +
  labs(subtitle = "displ vs cty",
       title = "kilométrage en ville en fonction de la capacité du moteur")

g <- g + geom_jitter(aes(col = manufacturer, size = hwy)) +
  geom_smooth(aes(col = manufacturer, method = "lm", se = F))
g
```


```{r}
ggplotly(g)
```









